version: '3'
services:
  web:
    image: php:7.4-apache
    container_name: task-web
    ports:
      - "88:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: task-db
    ports:
      - "3309:3306" #DEFINA SUA PORTA
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task-manager
      MYSQL_USER: user
      MYSQL_PASSWORD: pass